# This file was generated by GoReleaser. DO NOT EDIT.
cask "aispend" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "a85095a112687b72b7798cdd7115371ce4eb945b0791e22bad3626e6f1e6dcaa"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "390d9d05e8a1ee51b5b05abe88c967b15f3c5a7509cc7431e64ff02cc28a5dd9"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4852f51e373645147031bee6e8754340b435ee6fa866d4cd4e336d525806e89c"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "356a77ecd3eb30c78faaece6365e262b750bb07f404b5b3c06637b337e6a7c66"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aispend"
  desc "Local, explainable AI-coding spend — prices each turn against a pinned table, offline."
  homepage "https://github.com/cloudyali/ai-agent-spend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aispend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aispend"]
    end
  end

  # No zap stanza required

end
