# This file was generated by GoReleaser. DO NOT EDIT.
cask "aispend" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6cdbc58a8b6de355be531f0512671699c5550634017ec97fdeb33f2bc8a8adc6"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00efd8f93d63751afd48525406bda455c343639c3c735e85865237b857576665"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c689319767609d79ea9ccd07ceeee3a64a229eb2c4ec37adadb8789a1a1fe58b"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3a5187a883228a4ecf3df7987af0d0b2358626f00d9746e680fae9cbcecf60f"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aispend"
  desc "Local, explainable AI-coding spend — prices each turn against a pinned table, offline."
  homepage "https://github.com/cloudyali/ai-agent-spend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aispend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aispend"]
    end
  end

  # No zap stanza required

end
