# This file was generated by GoReleaser. DO NOT EDIT.
cask "aispend" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "8f43d5e8c3e8091980148fbc3e448e3710348dfe5dc73500458ab922e90766cd"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99936fdcc826ed050923969e5b64618101dd374f29be43849a423861c83ee32b"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6154fa2badae350cb8edcb5963516213fcb83e177c45e6848d01723d47226d5f"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1ec132379d1d2e43437c1998416c90e9eb5e50eb65d6f1eef6d967cc8759d70"
      url "https://github.com/cloudyali/ai-agent-spend/releases/download/v#{version}/aispend_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aispend"
  desc "Local, explainable AI-coding spend — prices each turn against a pinned table, offline."
  homepage "https://github.com/cloudyali/ai-agent-spend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aispend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aispend"]
    end
  end

  # No zap stanza required

end
